List<String> jobs = [
  'Software Engineer',
  'Registered Nurse',
  'Marketing Specialist',
  'Financial Advisor',
  'Teacher',
  'Mechanical Engineer',
  'Graphic Designer',
  'Sales Manager',
  'Chef',
  'Electrician',
  'Lawyer',
  'Social Worker',
  'Architect',
  'Pharmacist',
  'Civil Engineer',
];
